# Generated by Django 4.0.6 on 2025-02-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.URLField(max_length=255, unique=True)),
                ('ad_platform', models.CharField(blank=True, max_length=255)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
