# Generated by Django 4.0.6 on 2025-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.URLField(db_index=True, max_length=255, unique=True),
        ),
    ]
