# Generated by Django 4.0.6 on 2025-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_counter', '0002_alter_shortlink_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='ad_platform',
        ),
        migrations.AddField(
            model_name='shortlink',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='original_url',
            field=models.URLField(max_length=255, null=True, verbose_name='Оригинальная ссылка'),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='shortener',
            field=models.CharField(blank=True, choices=[('vk', 'vk_cc.ru')], max_length=255, null=True, verbose_name='Сервис сокращения ссылок'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество переходов по ссылке'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.URLField(db_index=True, max_length=255, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
