# Generated by Django 4.0.6 on 2025-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_counter', '0003_remove_shortlink_ad_platform_shortlink_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='original_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Оригинальная ссылка'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.URLField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
